--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/provsalt/LightningDeath
branches:
- master
projects:
  LightningDeath:
    path: ""
    libs:
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.2.0
  
...
