name: LightningDeath
api: 4.12.0
authors:
  - provsalt
  - muqsit
version: 1.4.0
src-namespace-prefix: provsalt\lightningdeath
main: provsalt\lightningdeath\Loader
permissions:
  lightningdeath.bypass:
    default: false
  lightningdeath.smite:
    default: op

commands:
  smite:
    description: Smite someone with lightning bolt.
    permission: lightningdeath.smite
    usage: "/smite <Target: Player>"
